services:
  quiosco:
    build: .
    network_mode: host
    environment:
      - PROXY_BASE=${PROXY_BASE:-}
    volumes:
      - ./config.json:/app/config.json
      - ./static/screenshots:/app/static/screenshots
      - ./data:/app/data
    restart: unless-stopped
